"""Data models for representing agent intent.

This module defines the structures used to capture the intent of the chat agent,
whether it is to call an action or ask for clarification.
"""

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field

from gradio_chat_agent.models.enums import ExecutionMode, IntentType, MediaType


class IntentMedia(BaseModel):
    """Represents media content attached to an intent.

    Attributes:
        type: The type of media (e.g., image, document).
        data: The content payload, typically a Base64 encoded string or URI.
        mime_type: The MIME type of the content (e.g., 'image/png').
    """

    type: MediaType = Field(..., description="The type of media (e.g., image, document).")
    data: str = Field(..., description="Base64 encoded content or URI.")
    mime_type: str = Field(..., description="The MIME type of the content (e.g., 'image/png').")


class ChatIntent(BaseModel):
    """Represents a structured intent generated by the agent.

    This is the primary unit of work passed from the Agent Layer to the
    Execution Engine. It encapsulates what the agent wants to do.

    Attributes:
        type: The category of intent (Action Call or Clarification).
        request_id: Unique identifier for this intent request.
        timestamp: Time when the intent was generated.
        action_id: The ID of the action to execute (if type is ACTION_CALL).
        execution_mode: The mode under which this intent was generated.
        media: Optional multimodal input associated with the intent.
        inputs: Dictionary of arguments for the action (if type is ACTION_CALL).
        confirmed: Whether the user has explicitly confirmed this action.
        question: The clarifying question (if type is CLARIFICATION_REQUEST).
        choices: List of valid options presented to the user (optional).
        trace: Diagnostic metadata for debugging and observability.
    """

    model_config = ConfigDict(use_enum_values=True)

    type: IntentType = Field(..., description="The category of intent (Action Call or Clarification).")
    request_id: str = Field(..., description="Unique identifier for this intent request.")
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="Time when the intent was generated."
    )
    action_id: Optional[str] = Field(
        None,
        pattern=r"^[a-z0-9]+(\.[a-z0-9]+)*$",
        description="The ID of the action to execute (if type is ACTION_CALL)."
    )
    execution_mode: Optional[ExecutionMode] = Field(
        None,
        description="The mode under which this intent was generated."
    )
    media: Optional[IntentMedia] = Field(
        None,
        description="Optional multimodal input associated with the intent."
    )
    inputs: Optional[dict[str, Any]] = Field(
        None,
        description="Dictionary of arguments for the action (if type is ACTION_CALL)."
    )
    confirmed: bool = Field(
        False,
        description="Whether the user has explicitly confirmed this action."
    )
    question: Optional[str] = Field(
        None,
        description="The clarifying question (if type is CLARIFICATION_REQUEST)."
    )
    choices: list[str] = Field(
        default_factory=list,
        description="List of valid options presented to the user (optional)."
    )
    trace: dict[str, Any] = Field(
        default_factory=dict,
        description="Diagnostic metadata for debugging and observability."
    )